"use strict";{(function(){var c=Math.floor;function a(){return c(2*Math.random())}//入力された文字列を３文字ごとに改行します
function b(a,b){for(resultArr=[],index=0,start=0,end=b;start<a.length;)resultArr[index]=a.substring(start,end),index++,start=end,end=start+b;return resultArr}var d=document.getElementById("canvas");if(d.getContext&&d){var e,f,g=d.getContext("2d"),h=document.getElementById("clientwidth").clientWidth,j=17,k=20,l=40,m=25,n=425,o=[],p=[],q=[],s=function(s){g.clearRect(0,0,d.width,d.height),g.strokeStyle="black",g.font="bold 15px 'Avenir'",g.textAlign="center";//選択肢を配列から取得してあみだのスタート地点に並べる
for(var B=1;B<=s;B++){e="prefix_"+B,o[B-1]=document.getElementById(e).value,words=o[B-1],words=b(words,3);for(var x=0;x<words.length&&2>x;x++)//y < 2で選択肢を2行に収める
10>s&&600>h?//狭い画面幅で少しでも見やすく
g.fillText(words[x],50*B,m+15*x):g.fillText(words[x],d.width/(s+1)*B,m+15*x)}q=[];//ここでsuffixArray2を空にする（重要）
for(var y=1;y<=s;y++)f="suffix_"+y,p[y-1]=document.getElementById(f).value;for(var C=0;C<p.length;C++)q[C]=p[C];//suffixArray2の配列（あみだに出力される結果）の順番をシャッフルする
for(var D=q.length-1;0<D;D--)r=c(Math.random()*(D+1)),tmp=q[D],q[D]=q[r],q[r]=tmp;//(Fisher-Yates shuffle)
for(var E=1;E<=s;E++){words=q[E-1],words=b(words,3);for(var F=0;F<words.length;F++)10>s&&600>h?g.fillText(words[F],50*E,n+15*F):g.fillText(words[F],d.width/(s+1)*E,n+15*F)}g.strokeStyle="#6e6e6e",g.lineWidth=2;for(var t,u=[],v=1;v<=j;v++){t=0,u[v-1]=[t];//ここで２重配列を作る
for(var G=1;G<=s;G++)G===s||0===a()||v===j?(u[v-1][t]=[0,0],t++,g.beginPath(),10>s&&600>h?(g.moveTo(50*G,v*k+l),g.lineTo(50*G,v*k+k+l),g.stroke()):(g.moveTo(d.width/(s+1)*G,v*k+l),g.lineTo(d.width/(s+1)*G,v*k+k+l),g.stroke())):(//同じ座標を同じ列に２つ置く(右回り用と左回り用)
u[v-1][t]=[G,G+1],t++,u[v-1][t]=[G,G+1],t++,g.beginPath(),10>s&&600>h?(g.moveTo(50*G,v*k+l),g.lineTo(50*G,v*k+k+l),g.lineTo(50*(G+1),v*k+k+l),g.moveTo(50*(G+1),v*k+l),g.lineTo(50*(G+1),v*k+k+l),g.stroke(),G++):(g.moveTo(d.width/(s+1)*G,v*k+l),g.lineTo(d.width/(s+1)*G,v*k+k+l),g.lineTo(d.width/(s+1)*(G+1),v*k+k+l),g.moveTo(d.width/(s+1)*(G+1),v*k+l),g.lineTo(d.width/(s+1)*(G+1),v*k+k+l),g.stroke(),G++))}var w=g.getImageData(0,0,d.width,d.height);g.strokeStyle="#e65353",g.lineWidth=3;for(var z=function(a){point=document.createElement("img"),point.src="\u4E38icon.jpg",point.setAttribute("class","point"),point.addEventListener("click",function(){g.putImageData(w,0,0),r=a;for(var b=1;b<=j;b++)10>s&&600>h?g.moveTo(50*a,b*k+l):g.moveTo(d.width/(s+1)*a,b*k+l),u[b-1][a-1][0]===a?(g.beginPath(),10>s&&600>h?(g.moveTo(50*a,b*k+l),g.lineTo(50*a,b*k+k+l),g.lineTo(50*(a+1),b*k+k+l),g.stroke(),a++):(g.moveTo(d.width/(s+1)*a,b*k+l),g.lineTo(d.width/(s+1)*a,b*k+k+l),g.lineTo(d.width/(s+1)*(a+1),b*k+k+l),g.stroke(),a++)):u[b-1][a-1][1]===a?(g.beginPath(),10>s&&600>h?(g.moveTo(50*a,b*k+l),g.lineTo(50*a,b*k+k+l),g.lineTo(50*(a-1),b*k+k+l),g.stroke(),a--):(g.moveTo(d.width/(s+1)*a,b*k+l),g.lineTo(d.width/(s+1)*a,b*k+k+l),g.lineTo(d.width/(s+1)*(a-1),b*k+k+l),g.stroke(),a--)):10>s&&600>h?(g.beginPath(),g.moveTo(50*a,b*k+l),g.lineTo(50*a,b*k+k+l),g.stroke()):(g.beginPath(),g.moveTo(d.width/(s+1)*a,b*k+l),g.lineTo(d.width/(s+1)*a,b*k+k+l),g.stroke());a=r}),document.getElementById("swich").appendChild(point),10>s&&600>h?(position=50*a-3,point.style.left=position+"px"):(position=d.width/(s+1)*a-3,point.style.left=position+"px"),A=a},A=1;A<=s;A++)z(A)},t=document.getElementById("main_contents"),u=document.getElementById("continue_amida"),v=document.getElementById("shadow"),w=document.getElementById("clear_word"),x=document.getElementById("amida_result"),y=document.getElementById("make_amida");y.addEventListener("click",function(){t.classList.remove("hidden"),y.classList.add("hyde")}),document.getElementById("description").addEventListener("click",function(){picture=document.getElementById("picture"),picture.classList.remove("hyde"),u.scrollIntoView(),picture.addEventListener("click",function(){picture.classList.add("hyde")})});var z=document.getElementById("number_list");document.getElementById("number_nav").addEventListener("click",function(){z.classList.remove("hidden"),v.classList.remove("hyde"),v.addEventListener("click",function(){v.classList.add("hyde"),z.classList.add("hidden")})}),document.getElementById("make_word_arr").addEventListener("click",function(){var a=document.getElementById("prefix_array"),b=document.getElementById("suffix_array");if(tree0=document.getElementById("selectnumber10").innerHTML,tree1=document.getElementById("selectnumber1").innerHTML,tree=tree0+tree1,tree=+tree,null!=document.getElementById("prefix_1")){for(preChild=a.childNodes,sufChild=b.childNodes,i=0;i<preChild.length;i++)//あみだの本数を途中で変えても、入力した文字列を確保する
o[i]=preChild[i].value,p[i]=sufChild[i].value;for(;a.firstChild;)//あみだの本数を変えるとき、既にある選択肢入力ボックスをclearする
a.removeChild(a.firstChild),b.removeChild(b.firstChild)}for(var c=1;c<=tree;c++)//選択肢入力ボックスをラジオボックスで入力した数だけ作る
prefix=document.createElement("input"),prefix.setAttribute("type","text"),e="prefix_"+c,a.appendChild(prefix),prefix.setAttribute("id",e),prefix.setAttribute("class","textbox"),0<o.length&&c<=o.length&&(prefix.value=o[c-1]),suffix=document.createElement("input"),suffix.setAttribute("type","text"),f="suffix_"+c,b.appendChild(suffix),suffix.setAttribute("id",f),suffix.setAttribute("class","textbox"),0<p.length&&c<=p.length&&(void 0===p[c-1]&&(p[c-1]=""),suffix.value=p[c-1]);p.length=b.childElementCount,w.classList.remove("hyde"),document.getElementById("select_list").classList.remove("hyde"),u.classList.remove("hyde"),v.classList.add("hyde"),z.classList.add("hidden"),document.getElementById("start").addEventListener("click",function(){if(null!=document.getElementsByClassName("point"))//あみだの本数を変えるとき、既にあるスタート丸ボタンをclearする
for(var a=document.getElementById("swich");a.firstChild;)a.removeChild(a.firstChild);s(tree),t.classList.add("hyde"),u.classList.remove("hyde"),x.classList.remove("hyde"),u.scrollIntoView()})});var A=document.getElementById("close");u.addEventListener("click",function(){t.classList.toggle("hyde"),x.classList.toggle("hyde"),A.classList.remove("hyde")}),A.addEventListener("click",function(){t.classList.add("hyde"),x.classList.remove("hyde")}),w.addEventListener("click",function(){inputs=document.getElementsByClassName("textbox");for(var a=0;a<inputs.length;a++)inputs[a].value="";0<o.length&&(o.length=0),0<p.length&&(p.length=0),u.scrollIntoView()})}})()}